<?php

namespace Sentinel\SchemaSentinel\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Sentinel\SchemaSentinel\Facades\Sentinel;

/**
 * Generates automated Markdown documentation for the current database schema.
 */
class DocsCommand extends Command
{
    protected $signature = 'schema:docs {--output=DATABASE.md : The filename of the documentation}';
    protected $description = 'Generate automated Markdown documentation for your database schema.';

    public function handle(): int
    {
        $this->components->info('Generating Schema Documentation...');

        $schema = Sentinel::parse();
        $output = $this->option('output');

        $markdown = "# 📊 Database Schema Documentation\n\n";
        $markdown .= "> Generated by [Laravel Schema Sentinel](https://github.com/clcbws/laravel-schema-sentinel) on " . date('Y-m-d H:i:s') . "\n\n";

        foreach ($schema as $tableName => $table) {
            $markdown .= "## 📋 Table: `{$tableName}`\n\n";
            
            $markdown .= "### Columns\n\n";
            $markdown .= "| Column | Type | Nullable | Default |\n";
            $markdown .= "| --- | --- | --- | --- |\n";

            foreach ($table->columns as $column) {
                $nullable = $column->nullable ? '✅' : '❌';
                $default = $column->default ?? '*NULL*';
                $markdown .= "| `{$column->name}` | `{$column->type}` | {$nullable} | `{$default}` |\n";
            }

            $markdown .= "\n";

            if (!empty($table->indexes)) {
                $markdown .= "### 🔑 Indexes\n\n";
                $markdown .= "| Name | Type | Columns |\n";
                $markdown .= "| --- | --- | --- |\n";
                foreach ($table->indexes as $index) {
                    $cols = implode(', ', $index->columns);
                    $markdown .= "| `{$index->name}` | `{$index->type}` | `{$cols}` |\n";
                }
                $markdown .= "\n";
            }

            if (!empty($table->foreignKeys)) {
                $markdown .= "### 🔗 Foreign Keys\n\n";
                foreach ($table->foreignKeys as $fk) {
                    $local = implode(', ', $fk->localColumns);
                    $foreign = implode(', ', $fk->foreignColumns);
                    $markdown .= "- `{$local}` -> `{$fk->foreignTable}({$foreign})` (On Delete: `{$fk->onDelete}`)\n";
                }
                $markdown .= "\n";
            }

            $markdown .= "---\n\n";
        }

        File::put(base_path($output), $markdown);

        $this->components->info("Documentation generated successfully: {$output}");

        return 0;
    }
}
